import 'package:material_ui/material_ui.dart';

import '../../../widgets/card.dart';
import '../../../widgets/row.dart';
import '../../../widgets/section_label.dart';
import '../frame.dart';

class LegalInfoScreen extends StatelessWidget {
  const LegalInfoScreen({super.key});

  static const _rows = [
    'Muse Supplemental Terms',
    'Muse Supplemental Privacy Policy',
    "Meta's AI Terms of Service",
    'Meta Terms of Service',
    'Meta Privacy Policy',
    'Meta Platform Technologies Supplemental Terms',
    'Meta Platform Technologies Supplemental Privacy Policy',
  ];

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final tt = Theme.of(context).textTheme;
    return SubPage(
      title: 'Legal info',
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 8),
          child: RichText(
            text: TextSpan(
              style: tt.bodySmall?.copyWith(color: cs.onSurfaceVariant),
              children: [
                TextSpan(
                  text: 'Responses are generated by AI. Some may be inaccurate or inappropriate. ',
                ),
                TextSpan(
                  text: 'Learn more',
                  style: tt.bodySmall?.copyWith(color: cs.secondary),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 12),
        MuseCard(
          children: [
            for (var i = 0; i < _rows.length; i++) ...[
              MuseRow(
                label: _rows[i],
                trailing: Icon(Icons.north_east, color: cs.outline, size: 20),
              ),
              if (i != _rows.length - 1) const Divider(height: 1),
            ],
          ],
        ),
        const SectionLabel('Meta Policies'),
      ],
    );
  }
}
